site_name: Mayzero的记录本
repo_url: https://github.com/Mayzero/blogNotes
theme:
  name: material

nav:
    - 前言: index.md   
    - cpp学习笔记: 
      - 基础知识: cpp学习笔记/Basic.md
    - GAMES101: 
      - Lecture01 计算机图形学概述: GAMES101/Lecture01.md
      - Lecture03 变换（二维与三维）: GAMES101/Lecture03.md
      - Lecture04 变换（模型、视图、投影）: GAMES101/Lecture04.md
      - Lecture05 光栅化（三角形的离散化）: GAMES101/Lecture05.md
      - Assignment01 作业1 旋转与投影: GAMES101/Assignment01.md

markdown_extensions:  
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  