site_name: Mayzero的记录本
repo_url: https://github.com/Mayzero/blogNotes
theme:
  name: material

nav:
    - 前言: index.md   
    - cpp学习笔记: 
      - 基础知识: cpp学习笔记/Basic.md
    - GAMES101: 
      - Lecture01计算机图形学概述: GAMES101/Lecture01.md
      - Lectre03变换（二维与三维）: GAMES101/Lecture03.md

markdown_extensions:  
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 


plugins:
  - search
  